### ISSUE TITLE
Install CLI doesn't work on Windows environment

### ISSUE THREAD

**Issue by thomasjetzinger** [domdinnes/node-flyway#19]
I'm trying to use the library in my project to perform some migrations on a test database. It looks like that there is an issue with path seperators, when you use it on windows.

When i try to call flyway.install I always get the following error:

> Attempted to log "[Error: ENOTDIR: not a directory, scandir 'C:\Development.....\flyway-8.2.2\native\mssql-jdbc_auth-9.2.1.x86.dll'] {
> errno: -4052,
> code: 'ENOTDIR',
> syscall: 'scandir',
> path: 'C:......'

The issue is this line:

![image](https://user-images.githubusercontent.com/1818920/225846248-3350f256-2535-4d79-ae45-035a57734e05.png)

`files[0].path` contains '/' as path separator and `path.sep` resolves to '\'.

Is there a way to resolve this issue?

**Comment by domdinnes** [comment]
Hi Thomas - I'll take a look at this and raise a fix. Watch this space!

**Comment by domdinnes** [comment]
https://github.com/domdinnes/node-flyway/pull/24 - resolved by this. @thomasjetzinger please let me know if you have any further issues.
