### ISSUE TITLE
Command options are not always quoted

### ISSUE THREAD

**Issue by cadam11** [domdinnes/node-flyway#29]
## Problem

There are two interrelated problems concerning building options for the shell command:

### 1. Running Flyway commands for a connection with a password that contains special characters breaks the command

e.g. manually running the failing command copied from debug log output (`DEBUG=*`)

```sh
/Users/cadam/.node-flyway/flyway-9.0.0/flyway -url="jdbc:sqlserver://localhost:1433; databaseName=F10; trustServerCertificate=true" -user=my-user -password=XPE9dgDLwW1!PMzJ3h(KECpD -locations="filesystem:./migrations" -schemas="__test_schema" migrate -outputType=json
```

Results in `event not found: PMzJ3h(KECpD`, presumably because the `!` in the password is trigging history substitution.

### 2. Running Flyway commands with options that contain shell-expansion characters breaks the command

```sh
/Users/cadam/.node-flyway/flyway-9.0.0/flyway -url="jdbc:sqlserver://localhost:1433; databaseName=F10; trustServerCertificate=true" -user=my-user -password=XPE9dgDLwW1PMzJ3hKECpD -locations="filesystem:./migrations" -schemas="__test_$PWD_schema" migrate -outputType=json
```

Creates a new schema that doesn't match the schema name provided.

```sql
SELECT CATALOG_NAME, SCHEMA_NAME FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME LIKE '__test%'
```

|CATALOG_NAME|SCHEMA_NAME|
|--|--|
|`F10`| `__test_$PWD_schema` |
|`F10`|	`__test_` |

Everything from the `$PWD` onward in the schema name is cut off– presumably due to shell variable expansion.

## Suggested solution

Alter the `convertToCommandLineString` to use single-quotes to prevent shell magic and to quote all string values regardless of whether they contain spaces.

Original code:

https://github.com/domdinnes/node-flyway/blob/fa89245589c4d5d386395609ee0bc22e9bb6846b/src/internal/flyway-command-line-options.ts#L48-L53

Suggested change:

```ts
 convertToCommandLineString(): string { 
     return `-${this.commandLineOptionKey}='${this.commandLineOptionValue}'`; 
 } 
```

Rationale being that quoting all values shouldn't ever hurt, even if it's sometimes unnecessary. I'm uncertain whether single quotes would cause issues in win32 platform, but could easily bake in a platform-specific piece to choose the appropriate platform-specific quote character.

**Comment by cadam11** [comment]
@domdinnes I'm totally sold on this project, largely based on your incredible work in creating the main README. I'm happy to open a PR for this change if you agree with the solution.

**Comment by domdinnes** [comment]
@cadam11 - thanks for raising this. I agree that this is an issue. Your fix seems sensible and I'm happy for you to raise a PR. I've just created a test case (and merged some missing functionality for the tests) that describes your issue. The test is currently marked as ignored but you can mark it as included in the test run when you make your change. https://github.com/domdinnes/node-flyway/blob/c14888ff647580ce2af56216d0aed72c334cbef6/test/integration/migrate.test.ts#L264-L311

You're welcome to add any additional tests if you think there are other scenarios that this case doesn't cover.

**Comment by cadam11** [comment]
Sounds good, PR is open. I didn't add more integration tests but did update the unit tests to cover the new quoting.

**Comment by domdinnes** [comment]
Merged - thank you for finding the issue!

**Comment by cadam11** [comment]
> Merged - thank you for finding the issue!

My pleasure– thanks for making a great library. Any idea when the next version will be published?
