### ISSUE TITLE
Publish updates to NPM

### ISSUE THREAD

**Issue by cadam11** [domdinnes/node-flyway#35]
I have a project that's now relying on this excellent library in production (despite the <1 version) and need some of the latest updates published for my user base.

Although it's possible to fork the repo and publish an update myself, I'd prefer to respect @domdinnes ownership here and kindly request that an NPM update be published as soon as practical.

**Comment by domdinnes** [comment]
Version `0.0.11` published: https://www.npmjs.com/package/node-flyway.

@cadam11 - I'm keen to continue developing this with the intention of rolling out a more battle-tested version `1.0.0`. I'm quite constrained on time but let me know if you'd like to work with me on some roadmap items or if you have any features you'd like to see yourself.
